const mockUser = {
  login: 'bibekdev',
  id: 75417994,
  node_id: 'MDQ6VXNlcjc1NDE3OTk0',
  avatar_url: 'https://avatars.githubusercontent.com/u/75417994?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/bibekdev',
  html_url: 'https://github.com/bibekdev',
  followers_url: 'https://api.github.com/users/bibekdev/followers',
  following_url: 'https://api.github.com/users/bibekdev/following{/other_user}',
  gists_url: 'https://api.github.com/users/bibekdev/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/bibekdev/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/bibekdev/subscriptions',
  organizations_url: 'https://api.github.com/users/bibekdev/orgs',
  repos_url: 'https://api.github.com/users/bibekdev/repos',
  events_url: 'https://api.github.com/users/bibekdev/events{/privacy}',
  received_events_url: 'https://api.github.com/users/bibekdev/received_events',
  type: 'User',
  site_admin: false,
  name: 'Bibek Chaudhary',
  company: 'bibekdev',
  blog: 'https://bibekdev.com',
  location: 'Lalitpur',
  email: null,
  hireable: null,
  bio: 'I am a full-stack developer and a CS major student. I have experience working on Reactjs, Nodejs, Laravel, MySQL, MongoDB, and blender.',
  twitter_username: null,
  public_repos: 36,
  public_gists: 0,
  followers: 2,
  following: 1,
  created_at: '2020-12-03T08:33:00Z',
  updated_at: '2022-05-04T07:29:01Z',
}

export default mockUser
